const Data = [
  "Data Structure",
  "Theory Of Computation",
  "Digital Electronics",
  "Control System",
  "Communication System",
  "Discrete Maths",
  "Digital Communication",
  "Applied Mathematics – IV",
  "Computer Organization and Architecture ",
  "Theory of Computation",
  "Database Management Systems",
  "Object Oriented Programming ",
  "Communication Systems",
  "Algorithms Design and Analysis ",
  "Software Engineering",
  "Java Programming",
  "Industrial Management",
  "Digital Communication ",
  "Communication Skills for Professionals",
  "Compiler Design",
  "Operating Systems ",
  "Computer Networks",
  "Web Technology",
  "Artificial Intelligence",
  "Microprocessor and Microcontroller",
  "Information Security ",
  "Software Testing and Quality Assurance",
  "Wireless Communication ",
  "Mobile Computing",
  "Machine Learning",
  "Human Values and Professional Ethics-II",
  "Advanced Computer Networks",
  "Cryptography and Network Security",
  "Ad hoc and Sensor Networks",
];
export default Data;
